### ISSUE TITLE
A big perf improvement via nim-markdown patch

### ISSUE THREAD

**Issue by ghost** [kyoheiu/Casa#1]
I've noticed your repo while searching for new Nim projects and also noticed that you were checking your project's performance. I  think that almost all of the runtime of Casa right now is spent in nim-markdown, which doesn't cache regular expressions so they get recompiled each time. With my PR https://github.com/soasme/nim-markdown/pull/50 time to execute `./casa build` goes down from ~2.75s to ~350ms (a ~8x improvement)

**Comment by kyoheiu** [comment]
Thank you for noticing this tiny and personal project!
I've also noticed the performance issue of nim-markdown, and am now trying to build my markdown parser (markdown -> kind of AST -> HTML), but it will take a long time to be completed.
Though I continue making the parser (cause that's fun, at least until now), it'd be great if nim-markdown's perfomance is improved. I'll check your PR.

**Comment by ghost** [comment]
the patch got merged :)
